name: waitathome
description: App created in the CodeVsCovid19 hackaton in Switzerland. With the hacking boys Nils, Hoang, Luca and Ralf.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.4+2
  json_annotation: ^3.0.1
  provider: ^4.0.4
  google_maps_flutter: ^0.5.11
  google_maps_place_picker: ^0.9.0
  pin_code_fields: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/map_style.txt
    - assets/images/marker_green.png
    - assets/images/marker_orange.png
    - assets/images/marker_red.png
    - assets/images/intro_customer.png
    - assets/images/intro_shop.png
    - assets/images/register_image.png